// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUg71i87D9wPa2iWUdL2PD5trH3zx9UsE',
    appId: '1:772969451694:web:a6180f9fac45dd552ddd3f',
    messagingSenderId: '772969451694',
    projectId: 'me2leads',
    authDomain: 'me2leads.firebaseapp.com',
    storageBucket: 'me2leads.firebasestorage.app',
    measurementId: 'G-SXVZ9RDKEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2I8NJ78pqu4Ceu3qG0s7tPN80nvv8v38',
    appId: '1:772969451694:android:0f73a92f1000ca0c2ddd3f',
    messagingSenderId: '772969451694',
    projectId: 'me2leads',
    storageBucket: 'me2leads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8g0vYwXexCGmFnlLPvJ1MmrH_lfU7IKU',
    appId: '1:772969451694:ios:8011dbcb07899abf2ddd3f',
    messagingSenderId: '772969451694',
    projectId: 'me2leads',
    storageBucket: 'me2leads.firebasestorage.app',
    androidClientId: '772969451694-9e71lctlt1rqdhavob115f16s35vroes.apps.googleusercontent.com',
    iosClientId: '772969451694-thhinvi6buauusle546su8irssfdb6t3.apps.googleusercontent.com',
    iosBundleId: 'com.debouana.me2leads.app',
  );

}